### PR TITLE
Add Delete component

### PR DESCRIPTION
**Pull request by feliperenan**
Hi @msaraiva 👋 

This PR adds this [bulma delete element](https://bulma.io/documentation/elements/delete/) to this project.

I started to play with bulma & surface so I decided to create some components, this is the first I've ever built - if that's ok for you others will come soon 🙈 .

Please, let me know what can be improved or if this Delete component worth to be added here at all.

Thanks for your work on surface, it looks amazing ✨

### CODE REVIEW

**Comment by msaraiva** [comment]
Hi @feliperenan!

It looks great!

> if that's ok for you others will come soon

Awesome! The more, the better :)

I have a couple of questions:

1. Why did you need to have both, a `link` and a `button` version?

2. Can you provide one, maybe two examples for the online documentation? They can just mimic the ones in Bulma's page and you don't have to add them to the `@moduledoc`. You can just copy/paste here as a comment. In the near future, the site's source will be public and authors will be able to add the examples themselves.

Thanks for contributing!

**Comment by feliperenan** [comment]
> Why did you need to have both, a link and a button version?

I started only with link but after a closer look at [bulma documentation in the combinations part](https://bulma.io/documentation/elements/delete/#combinations) I realized that they use the button tag there. That's why I implemented both. But maybe we could keep only the button version 🤔 . Let me know what you think then I will update accordingly.

> Can you provide one, maybe two examples for the online documentation? They can just mimic the ones in Bulma's page and you don't have to add them to the @moduledoc. You can just copy/paste here as a comment. In the near future, the site's source will be public and authors will be able to add the examples themselves.

Well, you mean the code example? There it is:

```Elixir
<Delete />
<Delete size="small" />
<Delete size="medium" />
# we might don't need this last one if we decide to use only button or link.
<Delete as="button" size="large" />
```

They will produce the HTML described here: https://bulma.io/documentation/elements/delete/#sizes

**Comment by msaraiva** [comment]
> I started only with link but after a closer look at bulma documentation in the combinations part I realized that they use the button tag there. That's why I implemented both. 

Oh, I see. I missed that in the docs :)

> But maybe we could keep only the button version 🤔 . Let me know what you think then I will update accordingly.

Yeah, I'm not sure if there's any practical difference so I think we could start with only one of them. Maybe `<a>` since it's the most used in Bulma's docs.  Then we can wait until someone needs it as a `<button>` and see how we should implement it. WDYT?

> Well, you mean the code example?

Yup. That's perfect.

**Comment by feliperenan** [comment]
Agree. So let's start with link and wait for more use cases to introduce the button one 👍 

The PR has been updated with this change 🙌

**Comment by msaraiva** [comment]
@feliperenan thanks! ❤️

**Pull request merged**
