### PR TITLE
Fix setting the `sort_by` on the column when supplying functions

### PR DESCRIPTION
**Pull request by Zurga**
Currently, the Column.sort_by prop would give a compile error if a function or tuple of functions was supplied as specified in the documentation. Therefore I changed the way the sorting is done. 

You can still set the `sort_by` prop as before, but internally the Column label will be mapped to the sorting function. When the column is clicked to sort it, the right sorting function will be found by looking up the column by its label and applying the sorting function given by its props.

### CODE REVIEW

**Comment by Zurga** [comment]
Anybody?

**Comment by msaraiva** [comment]
Hey @Zurga.

Thanks for the PR!

Sorry for taking longer to reply but we are on a search for a new maintainer for this project since @olivermt moved to `surface_bootstrap`. 

We're also considering having this project just as a set of sample components instead of a full-featured-production-ready suite.

It's really hard for the core team to work on such projects as we all use different JS/CSS libs and since we all have time constraints, we believe it's better to focus on `Surface` itself and let other projects (outside our umbrella) move on with the development of specialised components.

Anyway, we're still evaluating our options and we'll make an official announcement about it when releasing `v0.5`.

Thanks.

**Comment by Zurga** [comment]
Hey @msaraiva, thank you for the response, I understand that you might be busy, considering the v0.5 coming up. 

If you are looking for maintainers, I would be up for it! 

Currently I use this project for my own projects and have been adding some more components in my private fork. It would be a shame to just let this die a slow death. I really like the work that you have done so far and Surface has been a great technology to work with.

**Comment by olivermt** [comment]
Hey! I don't know why I didn't get an email that you posted this PR, as I have it on maximum notifications.
I didn't get the mail until @msaraiva tagged me.

As he said, I moved my efforts to SurfaceBootstrap and I would be very happy to give you the reigns both to this repo and to the hex package.

I'll need your hex username to transfer ownership.

**Comment by Zurga** [comment]
Hey Oliver,

No worries! My username on Hex is zurga.


Op di 8 jun. 2021 om 20:01 schreef Oliver Severin Mulelid-Tynes <
***@***.***>:

**Comment by olivermt** [comment]
Congratulations, you are now the owner of a well worn repository and hex package :)

**Comment by Zurga** [comment]
Thank you! I will do my very best! Exciting :)

Op di 8 jun. 2021 om 20:40 schreef Oliver Severin Mulelid-Tynes <
***@***.***>:

**Comment by msaraiva** [comment]
Hey @Zurga!

Have you already joined the `#surface` channel on slack?

**Comment by Zurga** [comment]
Hey @msaraiva!

No, not yet. I am having some trouble logging in to the elixir-lang slack workspace...

**Comment by msaraiva** [comment]
Hey @Zurga!

One thing we have to do is to leave the [surface_site](https://github.com/surface-ui/surface_site) completely independent from any component suite, this way they can be updated separately. 

Currently, the website depends on `surface_bulma` so we can show some examples like https://surface-ui.org/uicomponents/Button and friends, however, those examples and any other you come up with in the future for any other component should be moved to its own project.

I already created a project for `surface_bootstrap` called [surface_site_bootstrap](https://github.com/surface-ui/surface_site_bootstrap), which is basically a standalone phoenix project that uses the `surface_catalogue` to automatically present docs, API and examples from components without the need to update the website manually. You just have to update the version on mix and everything will be updated.

You can clone that project and replace any `surface_bootstrap` stuff with `surface_bulma` and everything should work just fine. As soon you and @olivermt give me the green light, I'll deploy them to `Gigalixir` and add the links to the main Surface website.

Please let me know if you need any further assistance.

Cheers.

**Comment by Zurga** [comment]
Hey @msaraiva,

Okay, got it, I will start work on the `surface_site_bulma` and move the examples to that repository.

**Pull request merged**
