### PR TITLE
publish to hex

### PR DESCRIPTION
**Pull request by michaelst**
I set the package up with hex.pm, I'm happy to add or transfer ownership

### CODE REVIEW

**Comment by olivermt** [comment]
You were a bit early with that, I've broken the API a few times precisely because we had not published yet.

If you could transfer to "olivermt" user that would be great, I'm working on 0.1.0 version as we speak and had planned to get it released today / tomorrow. I guess you stole that version thunder and I'll get 0.1.0 depublished from hex and release 0,1.1 so we don't have to signal a finished version (1.*) before we're ready.

**Comment by olivermt** [comment]
@michaelst any progress on transfering ownership? I had a pretty good plan for initial release this weekend and your hex highjacking put a solid wrench in that.

**Comment by michaelst** [comment]
I have transferred it now, I apologize about that. We needed a published version for our app as we don't use git sources.

**Comment by michaelst** [comment]
If it isn't ready you can always publish with a alpha or beta tag so people know the api can break

**Comment by olivermt** [comment]
@michaelst great stuff and thanks :)

I will let you know once I put out 0.2.0 because I will retire 0.1.0 shortly after since it's a breaking api change on Table.

**Pull request merged**
